// items.h - E22a / decision 38 (approved 2026-09-04, docs/persistence-service.md 25).
//
// WHAT THIS IS FOR. Nothing on the wire has ever moved an item. A player could loot a ghost's body, take
// everything, and the owning game never learned: the items stayed real on both machines, and a later
// re-announce rebuilt the ghost's inventory from the authority's snapshot so the looted items came back while
// the looter still had them. That is duplication, not transfer.
//
// THE RULE (part 1 of decision 38 - parts 2 and 3, requests for inventories we do not own and building
// containers, are E22b/E22c and are NOT implemented here). The game that OWNS a character is the only writer
// of that character's inventory. It hooks the four engine functions that see every item move, and sends one
// ITEM_MOVE per move on the GAME link. The other game applies it to its ghost through the engine's own
// add/remove calls, behind a re-entrancy guard so the apply does not ring back out as news.
//
// IDENTITY. An item has no stable id: the runtime `Item*` and its `hand` are per-process and the saved
// record's id is generated by the container. The only cross-game name for one item instance is
// (owner uid, section name, inventory x, inventory y) - POSITION IS THE IDENTITY - carrying the engine's own
// 0x2A record fields as the payload.
//
// MSG_CLOTHING (16) is NOT touched by this. It remains the one-shot worn-item snapshot at spawn-settle.
#pragma once
#include <string>
#include <vector>   /* B12: ItQueueReplayBox takes a journal entry's saved bytes */
#include "../common/bagwire.h"   /* inv3a: ItemRequestMsg / ItemConfirmMsg carry a handed-over backpack's contents */
#include "../common/ownerwire.h"   /* inv6: the stolen mark (item owner) as an identity both games understand */
#include "../common/groundkey.h"   /* inv5 phase 1: the ground key and ITEM_CONFIRM's refusal reason block */
#include "../common/itemstatwire.h"   /* items9: ITEM_MOVE op 4 CHARGES, op 0's [BAG1][OWN1] tail, snapshot detail stats */
#include "../common/shopwire.h"   /* T-164 B4-4: the shop block on ITEM_REQUEST / ITEM_CONFIRM (intercept at the trade call) */

namespace coop {

// One item move on the wire. `quantity` MEANS A DIFFERENT THING PER OP and that is deliberate - see the table:
//   op 0 ADD    - the stack size of the item that entered the slot.
//   op 1 REMOVE - the stack size that left the slot (informational; the whole stack goes).
//   op 2 QTY    - the surviving stack's ABSOLUTE quantity AFTER the merge, not the delta. (See items.cpp for
//                 why absolute: the engine's own merge arithmetic could not be read with confidence, and an
//                 absolute count cannot drift by an off-by-one on every merge the way a delta can.)
//   op 3 SPLIT  - how many units were taken OUT of the stack at that slot.
// The 0x2A record fields are carried for ADD only; every other op names an item the receiver already holds.
// E22c (P6e) / decision 38 part (3). `uid` 0 means THE INVENTORY IS A STORAGE BOX and `boxKey` names it:
// the owning building's instance id string (Building::instanceID.uid). A character uid is never 0, so the
// two cases cannot be confused, and the key rides at the END of the payload so protocol 37's field order is
// untouched for character moves.
struct ItemMoveMsg
{
    unsigned int uid;      // the OWNER CHARACTER's replicated uid, or 0 when `boxKey` names a storage box
    int op;                // 0 add, 1 remove, 2 quantity, 3 split, 4 charges (items9: uses left of the item at the slot)
    std::string section;   // the inventory section's name - part of the identity
    int x, y;              // the grid slot - part of the identity
    int quantity;          // see the table above
    // the 0x2A fields, ADD only (Item::_serialise 0x75FEA0 writes exactly these)
    std::string baseSid, companySid, materialSid, colorSid;
    float quality, charges;
    int functionKind, level, unique;
    // E22c-2 (P7n). THE CONTAINER KEY IS A POSITION KEY, not an instance id:
    //     <base record sid>@<sector x>,<sector y>@<x*10>,<z*10>,<y*10>      (tenths of a world unit)
    // built from what both games read identically out of the same file bytes - the building's FCS record
    // name (RootObjectBase::data +0x40 -> GameData::stringID +0x58) and its world position
    // (RootObjectBase::pos +0x48, through vtable slot 8). It is empty for a character move.
    std::string boxKey;
    // E22c-2 (P7n). `Building::instanceID.uid`, WHEN THE BUILDING HAS ONE - a CROSS-CHECK, never the name.
    // It is empty in a shipped town (the data files carry no instance ids and a zone with no zone file has
    // never been serialised), and where both sides do have one the receiver counts agreement and
    // disagreement against the positional match - which is the cheapest thing that could refute the key.
    std::string boxId;
    // inv6 (protocol 71): ADD only - the stolen mark as an identity (src/common/ownerwire.h), kind 0 = clean (nothing on the wire).
    coopmark::OwnerId owner;
    // items9 (protocol 78): ADD only - a backpack's contents (BAG1 rows), sent on a holder's GROUND ADD so a dropped pack is not
    // empty on the other game; empty = nothing on the wire.
    std::vector<coopbag::BagRow> bag;
    // bag23 part 2 (inv3 phase 3, protocol 81): THE MOVE IS INSIDE A PACK. `section`/`x`/`y` then name the cell INSIDE the pack, and
    // this names the pack: the parent's (uid's character / key's box) section and cell. A trailing 'BAGP' block (bagwire.h), after
    // everything else; has 0 = nothing on the wire.
    coopbag::BagPath bagPath;
    // bag23 part 2: NEVER ON THE WIRE - 1 = this op-0 ADD's pack-rows question was already asked (ItOp0BagRows); ItNetSendMove's late
    // look (every other op-0 publish site) then stands aside.
    int bagChecked;
    // inv6 D5-2: NEVER ON THE WIRE. A raw hand valid on THIS game (the taker's own engine marked its local object before the
    // drain undid the move) that ItCreateItem writes when `owner` is clean. {type, container, containerStamp, index, serial}.
    int ownerLocal;
    unsigned int ownerLocalRaw[5];
    // inv6 phase 2: NEVER ON THE WIRE - where `owner` / `ownerLocal` came from, for the counters only: 0 a message's OWN1 block (or
    // D5-2), 1 a list's OWNL tail (a box / bag / kit row: itemOwn2 row*), 2 an UNDO's re-create (the raw mark kept: undoKept only).
    int ownerFrom;
    // P105 build 2 (protocol 126, src/common/holdwire.h): the REQUEST TAG - this publication is the writer's effect of a HOLD / LAND
    // asked by the game in slot `rqtSlot` (request `rqtId`); an 'RQT1' trailer, announced by the op byte's high bit. rqtHas 0 = none.
    // The asker never applies one tagged with its own slot (it already shows that change).
    int rqtHas;
    unsigned int rqtId;
    int rqtSlot;
    ItemMoveMsg() : uid(0), op(0), x(0), y(0), quantity(0), quality(0.0f), charges(0.0f),
                    functionKind(0), level(0), unique(0), ownerLocal(0), ownerFrom(0), bagChecked(0), rqtHas(0), rqtId(0u), rqtSlot(-1) { std::memset(ownerLocalRaw, 0, sizeof(ownerLocalRaw)); }
};

// E22b / decision 38 part (2). A player touched an inventory this game does NOT own. The local half of the
// move has already been UNDONE by the time this is sent; the owner is being asked to make the move for real on
// its own character. `dir` says which way the item travels:
//   dir 0 TAKE - out of the OWNER's character (owner uid/section/x/y) and into OURS (taker uid/section/x/y).
//                The owner reads the real item and returns its record in the confirmation.
//   dir 1 GIVE - out of OURS and into the OWNER's character. The owner has to BUILD the item, so the 0x2A
//                record fields ride on the request itself.
// THE REQUESTER'S OWN COPY DOES NOT CHANGE UNTIL THE CONFIRMATION ARRIVES. That is the whole point: a local
// apply that can later be contradicted is how the same item ends up on both machines.
struct ItemRequestMsg
{
    unsigned int id;            // the requester's own counter - the confirmation names it and nothing else does
    int dir;                    // 0 take, 1 give
    // E22c: 0 means the owner half is a STORAGE BOX, named by `ownerBoxKey`. The RECEIVER must then hold the
    // box's patch of map (decision 38 part 3) rather than own a character, and its access policy must allow
    // the requester (decision 40 / E36). The TAKER half is always a character uid - a move whose OUR side is
    // a box cannot be asked for and is refused locally instead.
    unsigned int ownerUid;      // the character the REQUESTER does not own; the RECEIVER must own it
    std::string ownerBoxKey;    // E22c-2 (P7n): the owning building's POSITION KEY, when ownerUid == 0
    std::string ownerBoxId;     // E22c-2 (P7n): its instance id when it has one - a cross-check, never the name
    std::string ownerSection;
    int ownerX, ownerY;
    int quantity;
    unsigned int takerUid;      // the requester's own character - a ghost from the receiver's side
    std::string takerSection;
    int takerX, takerY;
    // T-164 211 (protocol 98): the TAKER half is a STORAGE BOX the requester holds when takerUid is 0 and this names it (its position
    // key). On the wire right after the owner-box block whenever takerUid is 0; empty = no taker (a ground put that names none).
    std::string takerBoxKey;
    // GIVE only (dir 1). Absent on a TAKE, where the owner reads them off the real item instead.
    std::string baseSid, companySid, materialSid, colorSid;
    float quality, charges;
    int functionKind, level, unique;
    // E35 (P6o) / decision 41 (approved 2026-09-04) - THE PRICE THE BUYER'S GAME COMPUTED.
    // `trade` 0 this is not a trade at all (the ordinary E22b/E22c request), 1 a PURCHASE (the item leaves
    // the shop and comes to us), 2 a SALE (the item leaves us and goes to the shop). `price` is cats, and it
    // is 0 whenever `trade` is 0 - and also when `trade` is set but the item's own value virtual could not be
    // called, which the sender counts as `priceUnavailable` rather than pretending the item is free.
    // WHY IT TRAVELS AT ALL: the price has no buyer-specific term, but three of its inputs are per-machine -
    // the town is looked up from the LOCAL player's position, the isPlayer bit comes from the LOCAL GUI
    // record XOR the LOCAL buy-back list, and the trader/trade-culture multipliers need a trade window to be
    // OPEN, which it never is on the peer (build/read-prices.md 5.2). A peer that re-derived it would get a
    // different number, silently. So the machine where the window is open names it, and the holder moves the
    // shopkeeper's cats using that number.
    int trade;
    int price;
    // inv3a (protocol 70; inv3-backpack-design.md D3(c)): GIVE only - when the item is a BACKPACK, what is inside it
    // (src/common/bagwire.h). The owner builds a new pack from the fields above and fills it from these rows BEFORE placing
    // it. Empty for every other item and for an empty pack.
    std::vector<coopbag::BagRow> bag;
    // inv6 (protocol 71): GIVE only - the given item's stolen mark, an 'OWN1' block after the optional BAG1 block; kind 0 = clean.
    coopmark::OwnerId owner;
    // bag23 part 2 (inv3 phase 3, protocol 81): the OWNER half is INSIDE A PACK - `ownerSection`/`ownerX`/`ownerY` name the cell in the
    // pack, this names the pack on the owner's character / box; `ownerBag.sid` is the record (S2-66: the owner looks for the same
    // record in the same pack when that cell no longer holds it). A trailing 'BAGP' block after the OWN1 block; has 0 = none.
    coopbag::BagPath ownerBag;
    int ownerBagDone;   // bag23 part 2: NEVER ON THE WIRE - 1 = ApplyItemRequest already made the S2-66 look on this copy
    int ownerBagShadowed;   // cell1: NEVER ON THE WIRE - 1 = that look found the record only SHADOWED; the take is refused
    // T-164 B4-4 (protocol 92): a SHOP TRADE asked at the trade call - the 'SHR1' block right after the trade block (src/common/
    // shopwire.h). has 0 = not one. With it the request is keyed on the trader's HOME (shop.homeKey, also in ownerBoxKey) and the
    // holder's shop branch answers it (ApplyShopRequest); no item has moved on the requester except its reservation / escrow.
    coopshop::ShopReq shop;
    // P105 build 2 (protocol 126, src/common/holdwire.h): dir 2 HOLD / dir 3 LAND - an 'HLD1' trailer. holdId: the hold (a HOLD's own
    // id; a LAND names the HOLD it puts down); holdHow: a LAND's how (coophold::kHow*), a HOLD's 1 = the whole item, 0 = `quantity`
    // units off the stack; holdSlot: the asker's own slot, which the writer copies into every publication's request tag.
    unsigned int holdId;
    int holdHow;
    int holdSlot;
    ItemRequestMsg() : id(0), dir(0), ownerUid(0), ownerX(0), ownerY(0), quantity(0), takerUid(0),
                       takerX(0), takerY(0), quality(0.0f), charges(0.0f), functionKind(0), level(0), unique(0),
                       trade(0), price(0), ownerBagDone(0), ownerBagShadowed(0), holdId(0u), holdHow(0), holdSlot(-1) {}
};

// E22b. The owner's answer. `ok` 0 is a REFUSAL and the requester changes nothing at all - the item simply
// stays where it was and the player may try again, which is decision 38's stated rule for a missed slot.
struct ItemConfirmMsg
{
    unsigned int id;
    int ok;                     // 0 refused, 1 applied on the owner's real character
    int quantity;
    // ok 1 only. On a TAKE these describe the item the owner just removed, and they are the only description
    // the requester will ever get of it.
    std::string baseSid, companySid, materialSid, colorSid;
    float quality, charges;
    int functionKind, level, unique;
    // E35 (P6o): the trade the HOLDER actually settled, echoed back. The requester debits or credits its own
    // purse by THIS number and never by the one it sent - if the holder refused the trade half, moved a
    // different amount, or is a build that does not carry trades, the requester must not move cats the other
    // side did not move. They are equal in the ordinary case; `shopTradeMismatch` counts when they are not.
    int trade;
    int price;
    // inv3a (protocol 70): TAKE with ok 1 only - when the item the owner removed is a BACKPACK, what is inside it, read off
    // the kept object right after the take. The requester fills its new pack from these rows BEFORE placing it.
    std::vector<coopbag::BagRow> bag;
    // inv6 (protocol 71): TAKE with ok 1 only - the mark the owner's item carried, an 'OWN1' block after the optional BAG1 block.
    coopmark::OwnerId owner;
    // inv5 (protocol 72): ok 0 only - WHY a ground request was refused (coopground::kGroundReasonNotHolder 1 / NotFound 2), a
    // 'GND1' block after the trade block; 0 = no reason given (every non-ground refusal).
    int reason;
    // T-164 B4-4 (protocol 92): the holder's answer to a shop request - the 'SHC1' block right after the trade block: its verdict, the
    // engine message the requester shows (0x70EC10), the units and cats moved, and the piece keys it wrote.
    coopshop::ShopCf shop;
    // M7b slice 2: NEVER ON THE WIRE - the player key of the game that ASKED (the request handler's sender); the answer goes back
    // to it (net::SendItemConfirm). toHave 0 = not set: the session peer on the session road, else not sent.
    unsigned int toKey;
    int toHave;
    // P105 build 2 (protocol 126): a LAND's answer says where the writer actually put the item - an 'LND1' trailer (ok byte 2).
    // landHas 0 = none; landWhere coophold::kWhere* (0 exactly as asked), landX / landY the square in the asked section.
    int landHas, landWhere, landX, landY;
    ItemConfirmMsg() : id(0), ok(0), quantity(0), quality(0.0f), charges(0.0f), functionKind(0), level(0),
                       unique(0), trade(0), price(0), reason(0), toKey(0u), toHave(0), landHas(0), landWhere(0), landX(0), landY(0) {}
};

void InstallItems();          // preload, MAIN THREAD: the four hooks
void ItemsTick();             // MAIN THREAD, every frame: drains the detours' ring, applies the ownership test and sends
void InvNetNoteAnnounced(void* ch, unsigned int uid);   /* inv2a, MAIN THREAD: an owned character's CLOTHING snapshot went out - the safety net's baseline is its inventory now */
int KitApplyBusy(void* ch, unsigned int uid);   /* T-1 B2 fold (review F2), MAIN THREAD: 0 = a pending kit may be applied to this copy; 1 an inventory window shows it or a pack of it, 2 an item from it is on the cursor, 3 a request against it awaits an answer */
void ItemsWorldTeardown();    // MAIN THREAD, from the store's teardown broadcast: the ring names the world being destroyed
void ApplyItemMove(const ItemMoveMsg& m, unsigned int fromPeer);   // MAIN THREAD: an ITEM_MOVE from another game; M7b slice 2: refused (itemMoveNotOwner) unless fromPeer owns the character / writes the box
// E22b, MAIN THREAD: a request from the peer to move an item on a character WE own. Applied through the
// engine's own path and NOT behind the re-entrancy guard, so our own hooks ring it and the ordinary ITEM_MOVE
// goes back out as usual - the request itself never writes anything on the wire.
// `fromPeer` is the SESSION PEER THE MESSAGE ARRIVED FROM, and it is not decoration: review-p5y MEDIUM-3 -
// the owner used to decode the taker half of the request and discard it, so nothing checked that the sender
// owns the character it is asking us to hand an item to. It is checked now (`requesterNotOwner`).
void ApplyItemRequest(const ItemRequestMsg& r, unsigned int fromPeer);
// E22b-2 (P6b), MAIN THREAD: the taker's MSG_ITEM_PLACED for a TAKE we granted. `ok` 1 destroys the object we
// have been holding alive since the request; `ok` 0 puts it back on our own character and publishes that.
void ApplyItemPlaced(unsigned int id, int ok, unsigned int fromPeer);
/* inv7c (D6), MAIN THREAD, from net SessionLeave: every escrowed TAKE goes back to the owner; the taker's re-send list is cleared. */
void ItemsEscrowSessionEnd();
/* inv7c fold (review 2/6), MAIN THREAD: every escrowed TAKE goes back to its owner now (the leave/quit save, a save start, a load). */
void ItemsEscrowHandBack(const char* edge);
/* inv7c fold (review 7), ANY THREAD: the session is ready (host: HELLO accepted; joiner: WELCOME) - the taker re-sends on the next tick. */
void ItemsSessionReady();
// E22b-2 (P6b), MAIN THREAD: the giver's MSG_ITEM_REVOKE for a GIVE we granted. It could not remove its own
// copy, so we remove and destroy the one we built - at the slot it actually landed in, base sid verified.
void ApplyItemRevoke(unsigned int id, unsigned int fromPeer);
// T-164 B4-4 fold 2, MAIN THREAD: MSG_ITEM_REVOKE carrying the shop tail ('SHK1', src/common/shopwire.h) - kind 0 the shop revoke, 1 the shop ack.
void ApplyShopTail(unsigned int id, unsigned int fromPeer, unsigned int epoch, int kind);
// E22b, MAIN THREAD: the owner's answer to a request WE sent. This is the only moment our own copy changes.
void ApplyItemConfirm(const ItemConfirmMsg& c, unsigned int fromPeer);   // M7b slice 2: taken only from the game the request was asked of (itemConfirmWrongSender)
// E22a TEST LEVER, MAIN THREAD, command channel only: give `count` of the item named by `baseSid` to the
// first LOADED character whose name contains `needle` AND whose uid this game owns, through the engine
// own add - so the transfer hook fires here and the other game ghost gains the item. Not a game feature.
bool ItemTest(const std::string& needle, const std::string& baseSid, int count);
int ItemsGiveMaterial(void* character, const std::string& sid, int qty, int* unitsOut);   /* help1: a refused construction material back to an own character - 1 taken, 0 not, -1 faulted; T-447: *unitsOut = the units placed (on 0, those placed before the refusal) */
// E34 TEST LEVER, MAIN THREAD, command channel only: take the item at (`section`, x, y) out of the first
// LOADED character whose name contains `needle` - ANY owner, the point being a character this game does NOT
// own - and put it into the local player's FIRST player-faction character, through the engine's own transfer
// calls so the hooks ring a REMOVE on the ghost and an ADD on the player carrying THE SAME Item object. That
// pair is what E22b recognises as a cross-ownership transfer, so this lever is what makes decision 38 part
// (2) reachable from the harness. `qty` 0 (or >= the stack) means the whole stack, which is the form that
// rings the pair; a smaller qty takes the engine's SPLIT path, which rings NO pair - see items.cpp.
bool ItemTake(const std::string& needle, const std::string& section, int x, int y, int qty);
// inv3a TEST LEVER, MAIN THREAD, command channel only: `itemgive <mine> <section> <x> <y> <ghost>` - the GIVE twin of
// itemtake: the item at (section, x, y) of THIS game's own character <mine> is moved into the OTHER game's character <ghost>
// through the engine's own calls, so the drain pairs it as a GIVE (E22b). `me` / `peer` name the lowest-uid own / other-game
// character; anything else is a name substring. Not a game feature.
bool ItemGive(const std::string& mineWho, const std::string& section, int x, int y, const std::string& ghostWho);
// inv3a TEST LEVER, MAIN THREAD, command channel only: `bagtest wear <who> <packSid|auto>` / `put <who> <sid> [count]` /
// `list <who>`. Returns the status line. Not a game feature.
std::string BagTestCommand(const std::string& arg);
// E22c (P6e) TEST LEVER, MAIN THREAD, command channel only: `boxtest <key substring> <base data sid> [count]`.
// Adds an item into the FIRST LOADED STORAGE BOX whose building instance id CONTAINS `needle`, through the
// engine's own add - so the item hooks ring a box move here, the drain publishes it when this game holds the
// box's patch of map, and the other game applies it by key. The hit line prints the FULL instance id so the
// next run can name that exact box. A test lever, not a game feature.
bool BoxTest(const std::string& needle, const std::string& baseSid, int count);
/* P17 TEST LEVER: boxtest's path into one chosen section - `input` = the section whose limit list names the item, any other text =
   the section of that name; no whole-inventory fallback after a refusal. MAIN THREAD, command channel only. */
bool BoxTestIn(const std::string& needle, const std::string& baseSid, int count, const std::string& sectionWant);
/* P17 TEST LEVER `jobtest work <characterUid> <buildingKey> [plain] [task=<n>]` (this game's own character gets the engine's own
   giveOrder 0x5D1640, default task OPERATE_MACHINERY 87, on the building) | `jobtest input <buildingKey> <itemSid> <n>
   [section=<name>]` (n of the item into the machine's input section) | `jobtest show <buildingKey>` (read-only). Every form prints
   the machine: name, product, inputs, sections. [JOB] lines. MAIN THREAD, command channel only. */
std::string JobTestCommand(const std::string& arg);
/* P43 TEST LEVER cagetest's candidates: up to `cap` loaded buildings (flat walk and furniture rows) whose record name says cage
   and whose class is UseableStuff, nearest to `from` first, with their position keys and names. Counts what was scanned, how
   many were named like a cage, and the first named one of another class. MAIN THREAD. */
int CageCandidatesNear(const float* from, void** out, float* distOut, std::string* keyOut, std::string* nameOut, int cap,
                       long long* scannedOut, long long* namedOut, std::string* otherClassOut);
// E35 (P6v) TEST LEVER, MAIN THREAD, command channel only: `buytest <key substring> [sid]`.
// Buys ONE item out of the FIRST LOADED SHOP COUNTER whose building instance id CONTAINS `needle` (a counter
// being a building whose UseableStuff::shopOwner carries a trader-squad bind), into the local player's first
// owned character, THROUGH THE ENGINE'S OWN PURCHASE CALL and with the money trade window OPEN - so the price
// is the number the game itself would have charged and P6o's trade detection reads 1. `sid` is optional and
// picks the first stock item whose base record id contains it. A test lever, not a game feature.
// P7d (review-p6v HIGH-1 / HIGH-3): `npcPath` != 0 forces `Inventory::buyItem` (what P6v always did, the
// path an NPC shopper takes); 0 tries the PLAYER's own right-click path, InventoryGUI::RClickAutoTrade, and
// falls back to buyItem with a stated reason. `allowStack` != 0 lets the pick take a stack of more than one,
// which buys a CLONE and rings no seller-side hook - a different experiment, and the line says so.
bool BuyTest(const std::string& needle, const std::string& sidWanted, int npcPath, int allowStack, int sell);   // T-1 B4-1: sell 1 = `buytest <key> sell [sid]`
bool PackBuyTest(const std::string& mode);   // par23 (parity P23): TEST LEVER - buy one item out of a wandering trader's pack
bool TraderList();   // T-1 B0: TEST, read-only - every loaded trader squad, who runs each member, pack digests ([TRADER] lines)
std::string KeeperListCommand(const std::string& arg);   // T-164 B4-0: TEST, read-only - `keeperlist [<x>,<y>|all] [<page>]`: NPC squads with a home building, each indoor piece with an inventory ([KEEPER] lines)
bool BuyTestKeeper(const std::string& pick, int sell, int cats);   /* T-164 B4-1: cats = the purse set first (-1 = not asked) */   // T-164 B4-0: TEST LEVER - `buytest keeper <n|ghost|own> [sell]`: BuyTest aimed at a keeperlist keeper, buyer walked to it first; ghost = home area held by the other game ([BUYTEST] keeper line)

// P7i (T232 section 2/section 3) READ-ONLY LEVERS, MAIN THREAD, command channel only. T232's `boxtest rebirth ...` and
// `buytest rebirth` both MISSED, and no verb in that build could say what the loaded buildings were called -
// `buildings` prints per-faction counts and not one instance id - so the only way forward was another guess.
//   `boxlist [<x>,<y>|all]`   every loaded building carrying an inventory: its POSITION KEY (E22c-2 / P7n -
//                             `key=`; the instance id follows as `id=` and is usually `(none)`), sector, class
//                             (PROBE P029), whether the inventory verifies, how many items it holds, and the
//                             held/mine answers the box road decides on.
//   `shoplist [<x>,<y>|all]`  every loaded SHOP COUNTER by `buytest`'s own test (a trader-squad bind at
//                             UseableStuff::shopOwner +0x360): its id, sector, whether the bind resolves to a
//                             loaded squad, the keeper's replication uid and name, and its stock count.
// No argument = ring 1 of the player's sector; `<x>,<y>` re-centres that ring; `all` = every loaded zone.
// 64 lines a call with a "... and N more" tail. They create, move and send nothing.
std::string BoxListCommand(const std::string& arg);
/* par1 (docs/design-loot2.md rev 2, 0.4): MSG_PARITY_REQ / MSG_PARITY_BOX arrived. MAIN THREAD (the session dispatcher). The
   holder queues the asked rows and answers kParityServeBudget per ItemsTick; the asker swaps a CONTENTS answer in at once. */
void TownPricesNote(const char* p, size_t n, unsigned int fromPeer);   /* T-619, MAIN THREAD: a TOWN_PRICES payload, by the session link or relayed by the world server (fromPeer a relay key) */
void ParityNoteReq(const char* p, size_t n, unsigned int fromPeer);   // M7b slice 2: fromPeer = the asker, the answers go back to it
void ParityNoteBox(const char* p, size_t n, unsigned int fromPeer);   // M7b slice 2 fold 1: a box's contents are taken only from its writer (parityBoxNotWriter)
std::string BoxDigestCommand(const std::string& arg);   /* par1: `boxdigest [<x>,<y>|ring|all]` - read-only: [PARITY] box key=.. items=.. digest=.. per box (flat + furniture) and a total */
std::string RestockNowCommand(const std::string& arg);   /* par2: TEST-ONLY `restocknow <x>,<y>` - arms the lever; holder squads only. T-1 B2: `restocknow wander near` */
std::string TraderSpawnCommand(const std::string& arg);   /* T-1 TEST-ONLY `traderspawn [dist]` - arms the lever: one wandering trader caravan beside this game's player through the engine's own createRandomSquad */
std::string BoxOpenCommand(const std::string& arg);      /* parity3: TEST-ONLY `boxopen <n>` - opens the n nearest non-player boxes one after another through the engine's loot open, then closes them */
void RestockNowDrain();                                   /* par2: the lever itself, at the K2 safe point (combat.cpp) */
void ItWanderRestockNote(void* ap);   /* T-1 B2: MAIN THREAD - note a wandering squad's packs and wearers around this game's restock of it */
/* T-1 B3 (owner 95), restructured (protocol 89): a squad's money rides MSG_SQUAD_LEAD (handoff.cpp). MAIN THREAD, all of them. */
int  KeeperPot(void* character, void** ownOut, int* catsOut);   // the squad's Ownerships::money via getOwnerships; 0 = not an NPC squad member / unreadable
int  KeeperPotAnnounced(void* character, void** ownOut, int* catsOut);   /* T-1 B3 fold (M2): KeeperPot net of this game's own in-flight predictions on a pot it ran at their send */
int  KeeperPotWritePod(void* own, int cats);                  // 1 = written and read back
int  KeeperPotsInFlight(std::vector<void*>* pots, int* unresolved);   // priced requests in flight (count); pots 0 = count only
void KeeperPublishCounter(void* counter);                     // the request road moved this counter's keeper's cats
void ReportParity();                                    /* par1: the [PARITY] REPORT line and an [ITEMS] REPORT line, from `report` */
void ResearchNoteBoxes(const std::vector<char>& payload);   /* loot2b: MAIN THREAD - a RESEARCH_BOX from the notebook: these boxes have rows (never lifted again) */
void ResearchTableReset();                                  /* loot2b: at the notebook WELCOME - its push re-sends every lifted box */
void ResearchModeMapBegin();                                /* loot2b: the host option `researchmode` on|off from the OPTIONS map (absent = off until L2c') */
void ResearchModeOption(const std::string& v);
void ResearchModeMapEnd(bool complete);
std::string ResearchModeStatus();                           /* loot2b: `researchmode` with no argument */
/* loot2c (docs/design-loot2.md section 2 steps 3-5, 4A row "L2c' show/take"; T362): per-player research copies in BOXES */
void ResearchNoteTakes(const std::vector<char>& payload);   /* MAIN THREAD - a RESEARCH_TAKE from the notebook (take rows; this player's own hide its copies) */
void ItemsLootNoteDestroy(const void* obj, int justUnloaded);                 /* ANY THREAD - GameWorld::destroy 0x798F50 is about to free obj: a LIVE copy is touched (main thread, outside the engine's brackets) or retired (inside them) - pointer compare only */
/* loot2c part A (user decision 2026-09-26, "yours on first touch"): the touch routes, stamped on a copy by the engine-call detour that saw it */
const int kLootTouchRemove = 1, kLootTouchSplit = 2, kLootTouchQuantity = 3, kLootTouchMergedAway = 4, kLootTouchPartial = 5, kLootTouchDestroyed = 6,
          kLootTouchLever = 7, kLootTouchUnseen = 8, kLootTouchDrain = 9, kLootTouchRoutes = 10;
void ItemsLootTouch(const void* item, int route);           /* ANY THREAD - an engine call touched `item`: a LIVE copy becomes TOUCHED (compare-exchange only; our own applying guard and the engine's brackets never touch) */
void ItemsLootCloseSignal();                                /* ANY THREAD, inside the engine's GUI close - marks only; the copies are retracted at the next items tick */
void ItemsLootRetractAll(int why);                          /* MAIN THREAD - every registered copy still in its box is destroyed now (zone deactivate, before the zone record is written) */
std::string BoxTakeCommand(const std::string& arg);         /* TEST-ONLY `boxtake <n> <sid|any>` */
std::string ItemTestTakeOneCommand(const std::string& arg);   /* inv2b: TEST-ONLY `itemtest takeone <n>` - one unit off the nearest held box's first stack of 2+ through takeOneItemOnly 0x749FF0 */
/* inv5 phase 1 (user-approved item fix #4; .modding/investigations/inv5-ground-items-design.md 3-5): ground items belong to the
   area holder. The ground is addressed by a G| key (src/common/groundkey.h) in the box-key field of the item messages. */
void ItemsInstallCopyDecisions();   /* kit3: preload, MAIN THREAD (from InstallItems): the eat task / auto-eat / haul / medic detours */
void GroundRefundBegin(void* building, int source);           /* MAIN THREAD, build.cpp detour_refund around 0x29DBD0: its Item::activate calls are noted (P3) */
long long GroundRefundMissedCount();                        /* P14 fold 1, MAIN THREAD: refund items the ground road never keyed (cumulative; the delta across a bracket) */
void GroundPickHoldCounts(long long* v5);                 /* P14 fold 2: the pickup hold's counts - expired, no slot, parked, parked+handed, parked+expired */
int  GroundPickHoldActive();                                /* P14 fold 1, ANY THREAD: an own ground pickup is between the engine's body and the main thread's ledger - squad writes wait (<= 1.5 s) */
int  GameDataSidPod(const void* gd, char* out, int cap);    /* P14 fold 1, POD: a GameData's stringID (1 = read) - a building material slot's record */
void GroundRefundEnd();                                     /* MAIN THREAD: the refund's items go to the one drop road (from = refund) */
void InstallGround();                                       /* preload, MAIN THREAD (from InstallItems): the drop detour 0x5C9CB0 and the pickup gate 0x34F2E0; P2/P3/P4 (ground5 fold 1 comment): the animal drop 0x5C9A10, the box / building spill 0x54DBA0 and Item::activate 0x75CE70 (the dismantle refund's items) */
void GroundDrain();                                         /* MAIN THREAD (ItemsTickDrain): the gate's snapshot, the detours' queue, the requester's timeouts */
std::string GroundTestCommand(const std::string& arg);      /* TEST-ONLY `groundtest list [r] | drop <section> <x> <y> | dropsid <sid> | pick <sid> [r]` */
void ReportGround();                                        /* `report`: the [GROUND] REPORT line */
int GrIsGroundKey(const char* key);                         /* 1 = a G| ground key */
void GroundApplyMove(const ItemMoveMsg& m);                 /* MAIN THREAD, from ApplyItemMove: GROUND ADD / GONE from the holder */
void GroundServeRequest(const ItemRequestMsg& r, unsigned int fromPeer);   /* MAIN THREAD, from ApplyItemRequest: a PUT / TAKE on the ground */
int GroundNoteConfirm(const ItemConfirmMsg& cf);            /* MAIN THREAD, from ApplyItemConfirm: 1 = the answer to one of our ground requests */
int GroundPutBackOk(void* item, const float* pos, const char* why);   /* inv7c fold: 1 = it was put back */
void GroundUndoTake(void* item, const float* pos, const char* key, int goneTold, int goneRoad, unsigned int goneRoute, unsigned int goneTarget,
                    unsigned int id, const char* why);   /* MAIN THREAD, from ItRollbackTake: an undone ground TAKE - back on the ground, ADD to the others */
void GroundPutBack(void* item, const float* pos, const char* why);   /* MAIN THREAD, from ItRollbackTake: a kept ground item goes back */
void GroundNoteKeptPlaced();                                /* MAIN THREAD, from ApplyItemPlaced */
void GroundWorldTeardown();                                 /* MAIN THREAD, from ItemsWorldTeardown (inv5p1 fold): the request rows, the unconfirmed drops and the detours' queue name the world that is going */
std::string ItemTestRefuseNextCommand(const std::string& arg);   /* T-1 B4-1: TEST-ONLY `itemtest refusenext [n] [reason]` - the HOLDER refuses the next n priced shop requests */
std::string ItemTestBoxMoveCommand(const std::string& arg);   /* T-164 211: TEST-ONLY `itemtest boxmove <fromBoxKey|peer> <toBoxKey> <sid|any>` - one whole stack across the authority line through the engine's own remove + add */
std::string CursorTestCommand(const std::string& arg);   /* p105h: TEST-ONLY `cursortest open <boxKey> | close | pick <c> <section> <x> <y> [all] | drop <c> <section> <x> <y> | back | list` - the engine's own cursor pickup / drop / return aimed at one square */
std::string BoxMoveCommand(const std::string& arg);
std::string HoldTestCommand(const std::string& arg);   /* P105 build 2: TEST-ONLY `holdtest delay <s> [n] | refusenext <gone|busy|policy> | list` - the writer keeps the next n HOLD / LAND requests unprocessed for s seconds (released in arrival order), refuses the next HOLD, or lists its rows */
void ItemsHoldSave(int phase, int onMainThread);       /* P105 build 2, the save pre-hooks (store.cpp): phase 0 before saveGame (every kept item back into its own square), 1 after it returns (lifted out again), 2 a saveLevelData outside a game save (a zone write: every hold put back and ended) */       /* p105h: TEST-ONLY `boxmove <boxKey> <section> <fx> <fy> <tx> <ty> [n]` - a move of n units (all when omitted) inside one box through the engine's own take-out + add */
std::string ItemTestRefuseHereCommand(const std::string& arg);   /* T-164 B4-2: TEST-ONLY `itemtest refusehere <gate> [n]` - the REQUESTER takes that refusal exit after the early put-back (and refunds) */
std::string ItemTestPackItemCommand(const std::string& arg);   /* T-215 (owner 177 a): TEST-ONLY `itemtest packitem [n]` - n sellable single items into this game's own seller's general grid */
std::string ItemTestConfirmDelayCommand(const std::string& arg);   /* give1: TEST-ONLY `itemtest confirmdelay <0..30>` - the OWNER holds each outgoing ITEM_CONFIRM that long */
/* inv6 TEST-ONLY levers (command channel, MAIN THREAD): `itemtest steal <n> [sid]` (a box stack into my first character through
   the engine's own RClickAutoTrade, so the engine sets the mark), `itemtest stolen <me|peer|name>` (read-only list of marked items),
   `itemtest givestolen <peer|name>` (GIVE the remembered stolen stack through the itemgive lever). [OWN] lines. */
std::string ItemTestStealCommand(const std::string& arg);
std::string ItemTestStolenCommand(const std::string& arg);
std::string ItemTestGiveStolenCommand(const std::string& arg);
std::string ItemTestSetCommand(const std::string& arg);   /* items9: TEST-ONLY `itemtest set <any|sid|section:x,y> [q=<0-100>] [ch=<n>]` */
std::string ItemTestMarkCommand(const std::string& arg);   /* inv6 fold (T401): TEST-ONLY `itemtest mark <sid|any> [<uid>]` - set an owner on my own item */
void ItemOwnerNoteCarried(const char* msg, const coopmark::OwnerId& o);   /* inv6: session.cpp - an 'OWN1' block went out on a message that was sent */
void ItemOwnerNoteBadRecv();   /* inv6 phase 2 (review-inv6 LOW): a RECEIVED owner block or tail that was malformed */
void ItemOwnerNoteRowsCarried(unsigned int n, unsigned int unknown = 0);   /* inv6 phase 2: n list entries went out marked in an OWNL tail; review-inv6p2 LOW: `unknown` of them as "owner unknown" (ownerSenderUnknown) */
void ItemOwnerOf(void* item, coopmark::OwnerId* out);   /* inv6 phase 2, MAIN THREAD: an item's mark as an identity (clean when none) */
/* bag23 part 1 (inv3 phase 2), MAIN THREAD: clothing.cpp's door to the pack reader (1 a pack - rows filled, possibly none; 0 not a
   pack; -1 its contents cannot travel whole, `*why` = kBagWhy*), that answer's name, and the COPY fill - every row placed that
   can be (its exact cell, else anywhere in its inner section = relocated), the rest destroyed and counted lost with a log line.
   `character` is the ::Character* whose scratch container makes the rows (0 = any). */
int ItemBagRowsOf(void* pack, std::vector<coopbag::BagRow>* rows, int* why);
const char* ItemBagWhyName(int why);
void ItemBagFillCopy(void* pack, const std::vector<coopbag::BagRow>& rows, void* character, int* applied, int* relocated, int* lost, const char* who);
/* kit2 (owner 102), MAIN THREAD: clothing.cpp's kit apply as the mod's own write - raise the applying-thread marker (returns the
   value it replaced) and put that value back; and the exact-cell placement in one section (items.cpp ItPlace with relocation:
   1 the exact cell, 2 that section's first free cell, 0 no room, -1 faulted - never a merge, never another section). */
long ItemApplyingEnter();
void ItemApplyingLeave(long prev);
long ItemApplyingPeek();   /* kit3 (kit2 review + T522, review D4): the marker's value now, unchanged */
int ItemPlaceInSection(void* sec, void* item, int x, int y);
int ItemOwnerApplyTo(void* item, const coopmark::OwnerId& o, const std::string& sid);   /* inv6 phase 2, MAIN THREAD: onto a fresh item; 1 applied */
void ItemOwnerNoteBadBlock();  /* inv6: session.cpp - an owner that would not encode (the item went clean) */
void BoxTakeDrain();                                        /* the boxtake move itself, at the K2 safe point (combat.cpp) */
/* loot2c internals shared by several regions of items.cpp - declared once here so every region names the one coop:: definition */
const int kLootWhyClose = 0, kLootWhyUnload = 1, kLootWhyAnswer = 2, kLootWhyServe = 3, kLootWhyPush = 4, kLootWhySave = 5;
void ItemsLootZoneOffThread();                              /* ANY THREAD - a zone deactivate off the main thread with copies registered: counted (retractMissedOffThread) */
void ItemsLootBeforeSave(int onMainThread, int which);      /* the saveGame 0x375220 (which 0) / saveLevelData 0x36DCA0 (which 1) pre-hooks: touched copies' takes recorded, the journal flushed, every untouched copy out of its box before anything is serialised (off the main thread: counted only) */
void ItemsLootWriteTripwire(int onMainThread);              /* the gdcSave pre-hook: a TRIPWIRE only - an untouched copy still in its box at a disk write is counted (lootLiveAtWrite, must stay 0) */
int  ItLootFindAny(void* item);                             /* the registry slot naming this item (any state), or -1 */
int  ItLootUnpublished(void* item);                         /* 1 = a registered copy the other games were never told of (LIVE or TOUCHED): the parity digest skips it */
int  ItLootBeforePublishRead(const std::string& key, int why);   /* THE helper before any read of a box's contents for a publish: -1 = do not read it this tick */
int  ItLootSplitTake(void* item);                           /* ItSplitAcquire: 1 = the split source was a live copy - taken whole, drop the split row */
void ItLootDrainBegin();
void ItLootAfterDrain();                                    /* after ItemsTickDrain: the close retract, the slot reaping */
void ItLootShowQueue(const std::string& key);
int  ItLootRetractBox(const std::string& key, int why);     /* copies retracted, or -1 = one is still in the box and could not be destroyed now */
void ItLootTakesReset();
int  ItLootRegCount();
int  ItLootDrainEntry(void* item, int op, int kind, int mine, const char* boxKey, int quantity);   /* 1 consumed (never published), 0 / -1 let through */
int  ItLootLeakGuard(void* item, int op);                   /* 1 = a registered copy was about to be published: blocked and counted (lootInjectLeak) */
int  ItLootWatchCount();                                    /* loot2c fold (3a): taken books still watched (not yet settled) */
int  ItLootWatchSplit(void* src, void* clone);              /* ItSplitAcquire: 1 = the split source is a watched book the other games do not know there - the clone is watched too, drop the split row */
void ItLootNoteTimeout(unsigned int id);                    /* ItPendExpire: a request that expired unanswered - a loot route's is counted and its book looked at again */
void ItLootWorldTeardown();                                 /* ItemsWorldTeardown: the unconfirmed takes, the watch list and the request ring are cleared (the journal file stays) */
void ItLootTick();
std::string ResearchListCommand(const std::string& arg);   /* loot2a (T333): `researchlist [<x>,<y>|all] [<page>]` - read-only: every research item (item+0x180 != 0) in every loaded box in the window */
std::string NearListCommand(const std::string& arg);   /* PROBE P068 (B1): `nearlist <x> <z> <r> [page]` - every loaded building near a point, no inventory filter */
// PROBE-START: P084
std::string CaptListCommand();   /* PROBE P084 (capt1, T337): `captlist` - read-only: shackles (LockedArmour in boots/armour, locked/broken), slave state, inSomething, KO per character, own and copies */
// PROBE-END: P084
std::string CaptureStateCommand(const std::string& arg);   /* P11 (test-only): `capturestate <uid>` - read-only: KO, slave state, slave owner, sections / records / shackle locks of one character */
std::string CaptureTestArm(const std::string& arg);   /* P11 (test-only lever): `capturetest <victimUid> [template] [taskType]` - spawn a slaver, wait for the KO, order the task */
std::string ChainTestCommand(const std::string& arg);   /* P11 f6 (test-only lever): `chaintest off <uid>` - setChainedMode(own, false, empty hand); P42: `chaintest on <uid> <ownerUid>` - setChainedMode(own, true, the hand of ownerUid) */
/* P42 (spawn.cpp RestraintWatch): the first shackle record worn in boots / armour - its section name and its DoorLock*. 1 worn with a
   readable lock, 0 none worn, -1 unreadable. */
int ShackleLockOf(void* c, char* sec, int secCap, void** lockOut);   /* c: a Character* */
void CaptureTestTick();   /* P11: MAIN THREAD, every frame from CommandChannelTick - nothing unless capturetest armed it */
std::string ShopListCommand(const std::string& arg);

// E22c (P6e) / decision 40 (approved 2026-09-04) - AUTHORITY IS NOT ACCESS. Which game APPLIES a change to a
// box is decided by decision 38 part 3 (the holder of its patch of map). WHO may take from or alter it is a
// different question, answered by a hosting option attached to the building's owner faction: shared (co-op),
// owner-only (PvE), locked (PvP). THIS BUILD HAS NO POLICY - the hook answers true for everybody, which is
// `shared` - and E36 fills it in. Every place that could refuse on access already routes through here.
// `requesterUid` 0 means this game's own player, asked before a request is sent.
bool BoxAccessAllowed(void* building, unsigned int requesterPeer, bool local);

/* ====== E45 (P8e): THE TWO THINGS THE DOOR ROAD BORROWS, so it carries no copy of either ======
   THE KEY.  ObjectPositionKey is ItBoxKeyBuild - the ONE P7n position-key builder (base record sid,
   sector, position in tenths of a unit) - reached from outside items.cpp.  `suffix` is appended
   verbatim when non-empty: the door road passes "gate" so a town gate is named by the
   GatewayBuilding's key plus that word and cannot collide with the gate building's own box key.
   `countIt` names the POPULATION a failure is booked to - 1 the item message path, 0 a lever walk,
   2 the door road - so a door key failure can never be read as an item-layer one (lesson 1).
   ANY THREAD, no allocation.  1 = built, 0 = not and the reason is counted.
   THE HOLDER.  AreaVerdictForDoor is ItAreaVerdictAt, the same decision-40 rule the box road asks,
   with the door population's own counters: 1 = this game holds this patch of map, 2 = another game
   does, anything else = no answer.  MAIN THREAD when it can be (one arm reads main-thread state). */
/* P8o-b (review-p8o H-1): `podPos` - 0 reads the position through the virtual getPosition, which is what
   every detour does and must keep doing; 1 reads the plain +0x48/+0x4C/+0x50 field the virtual itself
   copies (RootObjectBase::getPosition 0xD1DC0, Confirmed, not overridden below that class).  MODE 1 IS FOR
   A CALLER HOLDING A POINTER NO DETOUR HANDED IT - the door resolver, walking a memo a worker's zone
   teardown can outdate - because SEH catches a fault but not a call through a garbage vtable slot.  It is
   the SAME function either way, so both modes produce the same bytes for the same object. */
int  ObjectPositionKey(void* obj, char* out, int cap, const char* suffix, int countIt, int podPos);
/* build1h H1, MAIN THREAD: a building's owner class (src/common/boxowner.h kOwn*) and its owner's slot - items.cpp's
   ItFactionOwnerClass, for the placement hand-off in build.cpp */
int  BuildingOwnerClass(void* bld, int* slot);
/* par16 (parity P16), MAIN THREAD: who grows and harvests this farm - the production machines' writer (ItProdHolder's ladder:
   the owner's game while it is online and holds the area, else the area holder; the owner's hand-back gate). 1 this game,
   2 another game, 0 no answer (then nobody is held: both engines run as before). */
int  FarmWriterHere(void* b);
/* MAIN THREAD: who runs the steps of this production building (a mining node, a machine) - the production gate's writer (the
   owner's game while it is online and holds the area, else the area holder), kept per building key for 250 ms:
   coopfarm::kProdWriterHere 1 this game, kProdWriterOther 2 another game, kProdWriterNone 0 no answer yet. */
int  ProdStepWriterHere(void* pb);
/* ANY THREAD: 1 when the building's operate slot is ProductionBuilding::operate (a mining node or a production machine). */
int  ProductionBuildingIs(const void* b);
/* MAIN THREAD (farm.cpp, MINE_OP work): the engine's own ProductionBuilding::operate(who, amount), unhooked, in a
   fault guard. 1 ran; 0 not (the hook is not installed, or the engine faulted). */
int  ProdOperateRun(void* pb, void* who, float amount);
/* lever2 (TEST LEVER ONLY, buildtest farm): the farm's own box (ItBoxInventory) read the way ItParityContents reads a box:
   *stacks = the items in it, *quantity = their summed quantity. MAIN THREAD. 1 read; 0 not read (both -1). */
int  FarmBoxItemCount(void* b, int* stacks, int* quantity);
/* POSE (read-poses 2026-09-23): the building a key names on THIS game - ItBoxResolve, the box road's own resolver
   (cached, refuses two candidates and a world teardown). MAIN THREAD. 0 = not loaded here, or refused. */
void* ObjectByPositionKey(const char* key);
/* par16 fold #5, MAIN THREAD: the same answer with the CALLER'S OWN remembered pointer tried first - accepted only after the
   box cache's own two tests (the key read back from the pointer, and the pointer in this drain's walk of active zones or a
   live furniture row), else ItBoxResolve. A farm table that asks for every farm every 500 ms keeps its rows here instead of
   in the box cache's 16 rows, so it neither misses past 16 farms nor evicts a chest's row. */
void* ObjectByPositionKeyHint(const char* key, void* hint);
/* build1-e (recheck-build1d F2): WHY the last ObjectByPositionKey returned what it did. MAIN THREAD, read right after the
   call. Only kObjKeyNone means a complete, untruncated search found no candidate; every other 0 return may hide a live one. */
const int kObjKeyFound = 0;       /* one building answered */
const int kObjKeyNone = 1;        /* a complete walk: nothing in this game's loaded zones answers to the key */
const int kObjKeyAmbiguous = 2;   /* two or more candidates (or more than 8): refused */
const int kObjKeyTruncated = 3;   /* the walk could not list everything (LoadedBuildings limits, an unsettled generation, an empty walk) */
const int kObjKeyTeardown = 4;    /* the world is being torn down: no walk */
const int kObjKeyRefused = 5;     /* an empty or malformed key */
int ObjectByPositionKeyVerdict();
/* T-392 fold (review H1): the cap the resolver builds its candidate keys with (kBoxKeyCap). A key built with any other cap can
   differ from the resolver's (a long record name is hashed only when it does not fit), so build with this one. ANY THREAD. */
int BoxKeyCap();
/* P87 fold 1, MAIN THREAD: the sector a P7n key names (ItBoxKeyParse - no building is touched). 1 = parsed */
int  BoxKeySector(const char* key, int* sx, int* sy);
/* M7b slice 2 (T-197). MAIN THREAD: the sector a box / shop / ground key's thing is DECIDED in (a trader home's piece: the home's
   area; the ground: its key's sector), 1 = found. ANY THREAD: the relay map's holder of a sector, never this game (-1 unknown).
   MAIN THREAD: the player a box / shop / ground request goes to - a player-owned box's owner, else the area holder (-1 none). */
int  ItemKeySector(const std::string& key, int* sx, int* sy);
int  ItemAreaWriterSlot(int sx, int sy);
int  ItemRequestTargetSlot(const ItemRequestMsg& r);
/* P87 fold 2, MAIN THREAD: 1 = the two P7n keys name the same piece as ItBoxResolve matches one - same sector and base record, x and
   z within its +/-0.1 u window (ItBoxKeyNear; y not compared). 0 = not, or a key does not parse. No building is touched */
int  BoxKeyNearKey(const char* have, const char* want);
/* BED1 (T263/T264 poseBedUnresolved): the P7n key of the building whose interior LAYOUT made `piece`
   (Building+0x238 -> Layout+0x90, the engine's own furnitureParentBuilding 0xD5F60). 1 = built; 0 = not layout
   furniture, or no key. Guarded POD loads, then ObjectPositionKey (countIt 3, podPos 1). ANY THREAD. */
int  LayoutOuterKey(void* piece, char* out, int cap);
/* BED1: the hands of `outer`'s interior pieces - the boost::unordered_set<hand> at myInterior(+0x1F0)+0xE8 that
   createBuilding fills through 0x54E940 and collectInteriorBuildings 0x54A220 walks. Five u32 per piece into `ids`
   (type, container, containerStamp, index, serial - game/hand.h order), at most `cap` pieces; POD reads
   only, no engine call. Returns the count written. `*listed` = the set's own size (-1: no interior / unreadable),
   `*truncated` = 1 when the walk stopped before the set's end (cap, a bad node, or more nodes than the size).
   BED1-b (review M1): `*torn` = 1 when a zone deactivation (g_boxWalkGen, any thread) landed during the walk, or the
   walk ended with fewer nodes than the set's own size while nothing cut it; a torn walk returns 0 pieces. */
int  InteriorPieceIds(void* outer, unsigned int* ids, int cap, int* listed, int* truncated, int* torn);
/* review-build1f C1: the zone-walk generation g_boxWalkGen - a caller holding LoadedBuildings pointers re-checks it before
   touching them; a change means a zone was deactivated (its pieces may be freed). ANY THREAD. */
long long BoxWalkGen();
/* T-454 (owner 354 a), MAIN THREAD: the furniture registry (items.cpp ItFurnBuild) is out of date - a building piece newly exists
   on this game or flipped to complete. Sets the mark only; the rebuild stays lazy (ItFurnEnsure at the next lookup, at most once
   per drain). why: 1 placed (or a restore recreated it), 2 a copy made or adopted, 3 complete 0 -> 1. */
void ItFurnMarkStale(int why);
/* BED1-b (review M2): the five ids of a root object's OWN handle (RootObjectBase::handle +0x58: game/RootObjectBase.h, and
   0x54E940 / 0x9FD150 read obj+0x58 as the hand) - POD, no engine call. 1 read. */
int  ObjectHandIds(void* obj, unsigned int* ids5);
int  AreaVerdictForDoor(const float* pos);
/* P8n-c (review-p8n-b M-2): THE SAME VERDICT WITH THE LOAD WINDOW KEPT APART FROM A SETTLED ANSWER.
   AreaVerdictForDoor collapses kPicLoading into "mine" (ItAreaVerdictAt's first arm returns kBoxMine
   so a game can act on its own world while it loads), which is correct for a WRITE gate and wrong for
   a REFUSAL: a refusal has to be earned by a settled answer.  Returns one of coopdoor::kDoorArea*
   (Loading / Mine / Other / Nobody) - src/common/doorsync.h. */
int  AreaVerdictForDoorSettled(const float* pos);
/* B12 (decision 52): THE BOX FAMILY'S OUTAGE REPLAY. `payload` is one journal entry's saved ItemMoveMsg,
   exactly as the drain's refusal arm wrote it. Returns 1 when the entry is finished with (it went on the
   wire, or it could not be read back at all and keeping it would re-report it forever) and 0 when the send
   could not go out, which leaves the entry in the journal to re-arm at the next link-up. */
int  ItQueueReplayBox(const std::vector<char>& payload);
void ObjectKeyDoorCounts(long long* unbuildable, long long* sidHashed);
/* E45 (P8e-b, review-p8e C-1) - IS THIS OBJECT STILL IN THE ENGINE'S OWN ACTIVE-ZONE WALK?
   MAIN THREAD.  1 = the pointer still appears in the walk of the engine's active zones; 0 = it does
   not, or the walk could not settle.  IT DEREFERENCES NOTHING: it is a pointer compare against the
   list the box road already builds, and it is the ONLY test in this tree that says THE ENGINE STILL
   HAS THIS OBJECT.  A guarded read-back of an instance id says only "these bytes still read as that
   id", which a building the engine has DEACTIVATED but not destroyed passes every time (review-p6k
   HIGH-1, and F544 measured it).
   THE WALK IS SHARED WITH THE BOX ROAD - same list, same memo, same generation, so at most one walk
   per generation however many rows ask - which means `boxResolveWalks` counts walks caused by EITHER
   road from this build on. */
int  ObjectStillActive(void* obj);
/* E45 (P8o, T236g) - THE SAME MEMOISED ACTIVE-ZONE WALK, READ AS A LIST INSTEAD OF ASKED ABOUT ONE
   POINTER.  MAIN THREAD.  The door road has to resolve a KEY to a live door it has never seen move,
   which means looking inside each loaded building's door array, and ObjectStillActive answers
   membership only.  Ask the count first - that is the call which may walk, at most once per
   generation - then index 0..count-1; an out-of-range index answers 0 and never walks.  Same list,
   same memo, same generation as ObjectStillActive and the box road, so this adds NO second walk. */
int  ObjectActiveBuildingCount();
void* ObjectActiveBuildingAt(int i);

/* B10-b (review-b10 M-6): IS THIS POINT LOADED IN THIS GAME, RIGHT NOW - the box road's own live read, so
   the ZONE-FILE writer's first rung takes the same input a box takes instead of a 1 Hz sector flag. Asks the
   engine on the main thread; off it, or during a world teardown, it falls back to the locked grid and books
   that fallback apart (zoneLive[unavailable]), because a number whose accuracy differs between two paths must
   say which path it came from. pos is three floats. */
int  ItZoneLoadedHereLive(const float* pos);

std::string ItemsReport();    // the " items[...]=" token for the [STORE] REPORT line
std::string ItemsDetail();    // the thread/branch detail that follows it
/* snap1 (user decision 2026-09-26): `snapshot [<tag>]` - READ-ONLY. Arms one snapshot for the next whole in-game minute of the
   shared world clock; SnapshotTick (every frame, main thread) takes it at that instant and writes the [SNAP] block 64 lines a
   tick: one `char` line per uid-keyed character (own and copies), one `box` line per loaded non-player box, one `town` line per
   town a walked character names, then `done`. tools/parity_compare.py pairs the blocks of the two games. */
std::string SnapshotCommand(const std::string& tag);
void SnapshotTick();

}
